### ISSUE TITLE
Using in a Java/Maven project

### ISSUE THREAD

**Issue by nobeh** [JakeWharton/picnic#101]
Thanks for such a great library! I've been following the example at Java API at `RepresentativeJavaBuilderTest`.

The following is the dependency declaration in the `pom.xml`:

```xml
        <dependency>
            <groupId>com.jakewharton.picnic</groupId>
            <artifactId>picnic</artifactId>
            <version>${picnic.version}</version>
        </dependency>
```

with resolution to the version:

![CleanShot 2024-12-07 at 14 53 35@2x](https://github.com/user-attachments/assets/38663e30-89b6-41d1-aad8-e5928a16ed34)

I am fairly certain there's something I do not probably know about Kotlin libraries in Java+Maven, but here is what I get when trying in IJ:

```java
com.jakewharton.picnic.Table.Builder table = new com.jakewharton.picnic.Table.Builder();
```

Also getting the same compilation error via Maven Compile:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.13.0:compile (default-compile) on project jperf-toolbox: Compilation failure: Compilation failure:
[ERROR] /opt/nobeh/dev/jperf-toolbox/src/main/java/com/atlassian/jira/perf/data/DataLogger.java:[26,27] package com.jakewharton.picnic does not exist
[ERROR] /opt/nobeh/dev/jperf-toolbox/src/main/java/com/atlassian/jira/perf/data/DataLogger.java:[26,74] package com.jakewharton.picnic.Table does not exist

```

![CleanShot 2024-12-07 at 14 50 09@2x](https://github.com/user-attachments/assets/9c82d3c2-421a-4589-b068-084bb9d901a7)

My current setup:

```
Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
Maven home: /opt/nobeh/build/sdkman/candidates/maven/3.9.9
Java version: 21.0.5, vendor: Amazon.com Inc., runtime: /opt/nobeh/build/sdkman/candidates/java/21.0.5-amzn
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "15.2", arch: "aarch64", family: "mac"

```

What am I missing on how to properly use the library?

**Comment by JakeWharton** [comment]
So for Maven you probably need to use `picnic-jvm` as the artifactId.

**Comment by nobeh** [comment]
I knew it must be a noob situation. Thanks a lot.

For reference this is the correct dependency:

```xml
        <dependency>
            <groupId>com.jakewharton.picnic</groupId>
            <artifactId>picnic-jvm</artifactId>
        </dependency>
```
