### ISSUE TITLE
Support for table with external borders but no inner borders for top/bottom

### ISSUE THREAD

**Issue by onilton** [JakeWharton/picnic#13]
Picnic could be able to do build
```
┌───────────┬──────────────┐
│ columnA   │ columnB      │
├───────────┼──────────────┤
│ itemA1    │ B            │
│ itemA2    │ C            │
│ itemA3    │ D            │
└───────────┴──────────────┘
```

But right now I can only build
```
┌───────────┬──────────────┐
│ columnA   │ columnB      │
├───────────┼──────────────┤
│ itemA1    │ B            │
│ itemA2    │ C            │
│ itemA3    │ D            │

```
Using header (border=true) + body(borderLeft=true, borderRight=true)

**Comment by JakeWharton** [comment]
I believe the problem here is we do not allow the table itself to have a border. That can be fixed and then it collapsed with cell borders.

**Comment by JakeWharton** [comment]
You can technically already do this by simply checking if you're on the last row and giving it a bottom border. But it's something we could simplify.

**Comment by onilton** [comment]
> You can technically already do this by simply checking if you're on the last row and giving it a bottom border. But it's something we could simplify.

That's what I did as a workaround. Glad there is a better alternative now. I will try!
