### ISSUE TITLE
Columns are messed up with unicode chars

### ISSUE THREAD

**Issue by 4face-studi0** [JakeWharton/picnic#19]
## Expected behavior
Tables to be correctly drawn with unicode characters

## Current behavior
Tables are messed up with unicode characters

---

**Version**: 0.4.0
**OS**: MacOS BigSur - english language
**IDE**: IntelliJ Idea Ultimate 2020.2
**Kotlin**: 1.4.0
**Project type**: Multiplatform, JVM variant only for this module ( stdlib-jdk8 )
**JDK**: 14

### Chinese chars
![image](https://user-images.githubusercontent.com/37957092/90291510-5d41e080-de80-11ea-9923-826047421074.png)

#### TEXT:
```
┌──────────────────────────────────────────────────────────────────────────────────┬─────────────┬───────────────────┐
│  呀〈KIBA〉 ～暗黒騎士鎧伝～                                                                │  Year 2011  │  Tmdb id: 257171  │
├──────────────────────────────────────────────────────────────────────────────────┴─────────────┴───────────────────┤
│  Actors: Masaki Kyômoto, Mika Hijii, Leah Dizon, Mikoto Inoue, Raima Hiramatsu, Kazuhiko Inoue, Miz...             │
├────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│  Genres: Fantasy, Action, Adventure                                                                                │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```
### ANSI color code
![image](https://user-images.githubusercontent.com/37957092/90538744-400e5a00-e17f-11ea-81ff-508d0d9c3a7f.png)
![image](https://user-images.githubusercontent.com/37957092/90538810-59170b00-e17f-11ea-8179-db553d3ecc64.png)

#### TEXT EXAMPLE
`"\u001B[46mWelcome to My App!\u001B[0m"`

#### TEXT RESULT
```
┌───────────────────────────────────────────────────────────────────┐
│                                                                   │
│                    Welcome to My App!                    │
│                                                                   │
├──────────────────────────────────┬────────────────────────────────┤
│                                  │            commands            │
├──────────────────────────────────┼───────┬────────────────┬───────┤
│   Search a Movie by title        │   1   │   search       │   s   │
├──────────────────────────────────┼───────┼────────────────┼───────┤
│   Rate a Movie by id             │   2   │   rate         │   r   │
├──────────────────────────────────┼───────┼────────────────┼───────┤
│   Get suggested Movies for you   │   3   │   suggestion   │   g   │
└──────────────────────────────────┴───────┴────────────────┴───────┘
```

**Comment by JakeWharton** [comment]
Ignoring ANSI colors, for which I've reopened your other issue, I think there's two problems here:

 1. There is no measuring for graphemes wider than one. This is our bug.
 2. Many monospace fonts do not contain these characters and so they end up falling back to non-monospace characters. There's no much we can do about this. It happens in the terminal long after we've measured.

    In your specific example, you can see how the widths of the characters are not lining up with 1 or 2 columns.

    ![Screen Shot 2020-08-25 at 11 04 22 AM](https://user-images.githubusercontent.com/66577/91191999-712ce400-e6c3-11ea-896d-f077408d492f.png)

**Comment by 4face-studi0** [comment]
2. I sadly discovered that

1. After fixing that bug, am I right to expect the columns to be "almost aligned"?

I was wondering if there any kind of non-visible char that can be used to "balance" the row width.
Let's say something like:
* expect row to be 20 points
* current text is measured 11.5 points
* let's add 8 spaces + "half space"

**Comment by JakeWharton** [comment]
Looks like maybe http://unifoundry.com/unifont/index.html is a solution for the problem although it is not pretty 😬

**Comment by fardavide** [comment]
> Looks like maybe http://unifoundry.com/unifont/index.html is a solution for the problem although it is not pretty 😬

Quick dumb question: this solution can be applied only locally, right? I guess I can't ship it packed within my CLI app ( ? )

**Comment by JakeWharton** [comment]
Yes. There is likely no way to solve this in the general case. The font of the terminal is completely opaque to the library. The person may not even be using monospace!

**Comment by fardavide** [comment]
I see. Does this ticket still make sense to be open? Is there something more that can be done?

**Comment by JakeWharton** [comment]
I think in general, no, I think there's nothing we can do. If there's actual bugs around measuring (like #20 was) we can fix those, but ultimately there's not much we can do here except recommend fonts which are fully monospace, despite being exceedingly rare.

**Comment by knaeckeKami** [comment]
I think there actually might be a way to support this using a custom layout. (at least when assuming a font that renders emojis 2 characters wide, of course, this would break when a fully monospaced font is used)

1. We can count the number of "east asian full width" chars on each line and add this number to the length of this line (since these characters will be rendered two characters wide on most fonts, see [here](https://stackoverflow.com/a/63473262/1503432)

2. When drawing the cell, for every line in the cell, we add a zero-width character for every EAST ASIAN FULL WIDTH character to get rid of the extraneous spaces.

I ported this library to Dart and implemented this here:
https://github.com/knaeckeKami/barbecue/blob/emoji_support/lib/src/text_layout.dart#L98

I didn't test it thoroughly yet, but for my use cases, it works.

And since this can be implemented as TextLayout, it's an opt-in feature, users of this library could choose whether they want to use the EmojiAwareLayout and risk breaking users which use a fully monospaced layout, or if they stick with the SimpleLayout. (and refrain from using EAST ASIAN FULL WIDTH characters)
