### ISSUE TITLE
How to use picnic in Java

### ISSUE THREAD

**Issue by almogtavor** [JakeWharton/picnic#32]
I wonder if there is a simple quick start example for the usage of picnic in Java? A minimal introduction to Java usage would be great.

**Comment by vanniktech** [comment]
https://github.com/JakeWharton/picnic/blob/3207d22101f7832e99fad4a8ebcb3b266b25a28c/picnic/src/test/java/com/jakewharton/picnic/RepresentativeJavaBuilderTest.java

**Comment by JakeWharton** [comment]
Yep see above link.
