### ISSUE TITLE
Jar for 0.6.0 in maven central is missing the .class files

### ISSUE THREAD

**Issue by stephenbyrne-wk** [JakeWharton/picnic#43]
[The 0.6.0 jar in maven central](https://repo1.maven.org/maven2/com/jakewharton/picnic/picnic/0.6.0/picnic-0.6.0.jar) is missing the `.class` files.

**Comment by JakeWharton** [comment]
If you are consuming the project in a non-Gradle build system you need to use the `picnic-jvm` artifactId rather than just `picnic`. Unfortunately I can't figure out how to make Gradle have the default artifact be the JVM one to maintain compatibility, sorry. I can try to look into it again...

**Comment by stephen-byrne** [comment]
Using `picnic-jvm` works. Thank you.
