### ISSUE TITLE
Legacy mode

### ISSUE THREAD

**Issue by vanniktech** [JakeWharton/picnic#44]
When using picnic 0.6.0 I'm getting:

> The dependency com.jakewharton.picnic:picnic:0.6.0 was published in the legacy mode. Support for such dependencies will be removed in the future. See https://kotl.in/0b5kn8 for details.

Seems like tooling needs to be udpated, a new release needs to be cut and then we're all good.

**Comment by JakeWharton** [comment]
Will do

**Comment by JakeWharton** [comment]
https://github.com/JakeWharton/picnic/releases/tag/0.7.0
